from __future__ import annotations

import argparse
import hashlib
import json
import secrets
import string
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from collector.config import get_settings
from collector.db import Database


def generate_api_key(length: int = 40) -> str:
    alphabet = string.ascii_letters + string.digits
    return ''.join(secrets.choice(alphabet) for _ in range(length))


def hash_api_key(api_key: str) -> str:
    return hashlib.sha256(api_key.encode('utf-8')).hexdigest()


def main() -> None:
    parser = argparse.ArgumentParser(description='Provision snapshot lookup API client')
    parser.add_argument('--client-id', required=True)
    parser.add_argument('--nickname', required=True)
    parser.add_argument('--status', default='active', choices=['active', 'revoked'])
    parser.add_argument('--api-key', default=None, help='Optional explicit API key; autogenerated if omitted')
    args = parser.parse_args()

    api_key = args.api_key or generate_api_key()
    api_key_hash = hash_api_key(api_key)

    db = Database(get_settings().database_url)
    with db.connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO collector.snapshot_api_clients (
                    client_id, nickname, api_key_hash, status, created_at_utc, updated_at_utc
                ) VALUES (%s, %s, %s, %s, NOW(), NOW())
                ON CONFLICT (client_id)
                DO UPDATE SET
                    nickname = EXCLUDED.nickname,
                    api_key_hash = EXCLUDED.api_key_hash,
                    status = EXCLUDED.status,
                    updated_at_utc = NOW()
                """,
                (args.client_id, args.nickname, api_key_hash, args.status),
            )
        conn.commit()

    print(json.dumps(
        {
            'client_id': args.client_id,
            'nickname': args.nickname,
            'status': args.status,
            'api_key': api_key,
            'api_key_hash': api_key_hash,
        },
        ensure_ascii=False,
        indent=2,
    ))


if __name__ == '__main__':
    main()
